[package]
name = "git-stack"
description = "Stacked branch management for Git"
version = "0.8.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gitext-rs/git-stack.git"
documentation = "https://github.com/gitext-rs/git-stack.git"
readme = "README.md"
categories = ["command-line-interface", "development-tools"]
keywords = ["git", "cli"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/gitext-rs/git-stack/compare/{{tag_name}}...HEAD", exactly=1},
]

[dependencies]
git2 = { version = "0.14", default-features = false, features = ["vendored-libgit2"] }
git-config-env = "0.1"
clap = { version = "3.1", features = ["derive"] }
clap-verbosity-flag = "1.0"
log = "0.4"
env_logger = { version = "0.9", default-features = false, features = ["termcolor"] }
yansi = "0.5.0"
concolor = "0.0.8"
concolor-clap = { version = "0.0.9", features = ["api_unstable"] }
proc-exit = "1"
eyre = "0.6"
human-panic = "1"
termtree = "0.4"
indexmap = "1"

git2-ext = "0.0.5"
git-branch-stash = "0.8"
humantime = "2"
itertools = "0.10"
ignore = "0.4"
bstr = "0.2"
maplit = "1"
petgraph = "0.6.0"
downcast-rs = "1.2.0"

[dev-dependencies]
git-fixture = { version = "0.2" }
assert_fs = "1"
